server:
  port: {$PORT}
  servlet:
    contextPath: /api

spring:
  application:
    name: wizards
  datasource:
    url: jdbc:postgresql://c6sfjnr30ch74e.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d7qgk2qentnd25?sslmode=require
    username: u6ge3dk3fa60hp
    password: pf68b0cb4ae4056a89849b744955caab5ac6dc87dbd24069562a0fda16f6d2e31
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 20000
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate.ddl-auto: update
